language: node_js
node_js:
  - "node"
services:
  - xvfb
  - postgresql
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - psql -c 'CREATE DATABASE twitter;' -U postgres
  - psql -f schema-and-seed-data.sql -d twitter -U postgres
  - npm start &
cache:
  directories:
    - "node_modules"
